### PR TITLE
[HP] Added lexer

### PR DESCRIPTION
**Pull request by HPaulson**
- Tokenizes .lydo file
   - Accounts for basic/common errors & reports accordingly
- Added unit testing
- Added typings & moved to ts files
- Added CI action for deno fmt & lint
- Removed in-file license (repo-level LICENSE file is sufficient)
- Fixed syntax errors in std
----
Known bugs (Future PR):
- Strings do not retain beginning whitespace
- Strings do not retain newlines (replaced with a space)
- Using a valid number as an identifier will tokenize as NUMBER instead of IDENT

### CODE REVIEW

**Comment by lamersc** [comment]
Just fix discussed issues from yesterday with string parsing, new lines and line numbers; we should be ready to go ahead with the parser stage about that and develop AST tree from tokens

**Review by lamersc — COMMENTED** [review]
Just fix discussed issues from yesterday with string parsing, new line parsing and line numbers; we should be ready to go ahead with the parser stage about that and develop AST tree from tokens. Amazing work so far 👍

**Comment by HPaulson** [comment]
@lamersc PR should be ready for review.

There are still two known bugs with string tokenization, but they are minor and will be fixed in a future PR. See commit notes for more detail.

**Review by lamersc — APPROVED** [review]
LGTM!

**Pull request merged**
